spring.application.name=mascota

# Configuración de base de datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/sanos_y_salvos_db
spring.datasource.username=tu_usuario
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Mostrar las SQL en consola (útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de tipos de datos (para Instant/LocalDateTime)
spring.jackson.serialization.write-dates-as-timestamps=false

server.port=8080