spring:
  datasource:
    url: jdbc:h2:mem:testdb;TIME ZONE=UTC;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  #  security:
  #    user:
  #      name: admin
  #      password: admin123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

#  data:
#    redis:
#      host: localhost
#      port: 6379